//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH350
{
	using System.Threading.Tasks;
	[TestFixture]
	public class FixtureAsync : BugTestCase
	{
		// We pass an Int32 id to Load and expect an exception, since the class
		// uses Int64 ids.
		[Test]
		public async Task LoadingAsync()
		{
			object parentId;
			using (ISession session = OpenSession())
			{
				SecurityDomain parent = new SecurityDomain();
				parent.Name = "Name";
				parent.ChildDomains.Add(new SecurityDomain());

				parentId = await (session.SaveAsync(parent));
				await (session.FlushAsync());
			}

			try
			{
				using (ISession session = OpenSession())
				{
					Assert.ThrowsAsync<TypeMismatchException>(() => session.LoadAsync(typeof(SecurityDomain), 1));
				}
			}
			finally
			{
				using (ISession session = OpenSession())
				{
					await (session.DeleteAsync("from SecurityDomain"));
					await (session.FlushAsync());
				}
			}
		}
	}
}